/**
 * Which of 16,000 evenly spread points on the globe fall on land — one bit
 * per point, base64. The points themselves aren't stored: `fibonacciPoint`
 * regenerates the exact same spread (a Fibonacci sphere) on the client, so
 * the whole dotted Earth costs under 3 KB instead of a map library.
 *
 * Generated once from Natural Earth's 1:50m land polygons (via the
 * world-atlas package) with d3-geo's geoContains — not a runtime dependency.
 */
export const LAND_POINT_COUNT = 16000;

const LAND_MASK_B64 = "AAAAAAAAABAAQkJIAAhLIQMkJIWEhIAEEBJCAkDAAZk6IQNgYAAMhJAjMjJADsTYgRk5MkNi7sjMGplpMfEtZv3Mpr3WNvf6Sttf+ztff+Xt//2Vt7/+9t732tv5/ztvf+ft/P+dt/v2Vv7+ylv5eztv9++tvN21s/L3Vsbu31t5Oysn5e+snJ2Xk3J3VmbOzUm5OSMr5+ak7JyR03JzRn7OzUmZOSMv5+aE7Jy70zNzQn7OzInZOTG3Z+bE/Jyb03NzRm7Pzen5OTU35+bk3J6b03NzSm7Ozcm5OTW35+bU3Jybk3Nzak7Ozek5OTWn5+b0nJyb03Nzam7Pyak5OTW35+bUnJybU3Nyam7Ozam5OTWn4+bUnJybUXNyakbGzak5OTGj5ubUnIybUXNyakbNzeg5OTOj5uTEjIqRkXN6akbFyYgZNSOj5+TEjIqREXNqTk7FyYkZNScmZtSEnIqTE3NqRkzMyYk5FSMmZtSEmIiRE3NqRkzOiQk5FSMmZtSUmJyTE3NqRk7MqAk5ESOmZtSEjJ6RUzJiRkzNiAkZPSOmZuSEmJoREzJqRkzN6AkZNSOmZNSEmJoREzJqRkzJ6Ak5NSOmZNSEmJLRUzJqTkzJqAk5JaemZNSEmJJRU3JqTkzJqSkxJaem5NSUmJJTUnJqSk3JKSkxJaem5JSUmJJTUGJKSknJKSkxJaek9NSUkpJTUGJKSknJKSklJaekxFSckpJTUGpKSknJKCglJaekxBSUkpJTUEoKSkmJKCklBaek1BSckgJTUEoKSkmpKCklBaeklBSckgJTUkoKSkmpKCklBaamlBSUkkJTUkoKSEmpoSElBaaklBSQmkJBUkoKTEmhKSA1BYaElFSQkkJBQEoqDAkpISA1hYaklBSQkkJBQGoqDAmpKSAlhYaA1BQQklJBQGoKCgGpKSAkhYaA1BQQglJBQEoKCwGpISAEhYKA1BQUglJCQGgKCQGpKSAUhYCA0BQWglpCQCgKCQGpKSAEpYCAUBQWAlJCQCgKSQEhICAEpYCAUBQSAlJQQAgKCQEhICQEpICAUBQSAkJAQQgKCQUhISQEpISCUBQSAkJCQQhoCQUhoCwEhISCUFASCkJCQShICQUhqCwEpISCUFASCkJAUQgICQUhoCwUpISCEFASCkJAUQgICQUhoCQUhICCEFASCkJAUSgoSQUBoCQUlYCCEFASigJAQSgoQAUBoCQVFYCCAFAQCgJAQSgqQAUBoCAVFICCUFQACgJAQSgqAAUBqAAVBICCQFQACgJAQagqAAWBqAAVBICiUFQACgJRASgoAAWBqAAVBKACUFQACgJRASoqAEWgqAAVBKICUFAACgJRESooAAWgqAAVFKICUFAACoBRASooBAWgoAgVFKIiVFCECkhRESooBgWkoAgUEIICUFQMCkhBESooBgXkqAgUEIICUFQMCkhBESogBkWkoAgUEIICUFAMCkhBESogBkWkoAgUEIICUECMCkhBESogBAWgoAgVkIIiUECICkhBESggRAWgoBAUkIICUEAMCkBBASggBAWggBAUkKICUEAICkBBASggBAWggBAUgIICUEAICkBBASggBQWggBAUgIIiUEAICkABASgCBQWggBAUgYICUAQKCkABISgKBUWgiBAUgIICUAQKCkARISgABUWgiBQUgCICUBQKCkARISgCBUWgKBQUgCIDUAQKikBRCSgCRUSgKBQUgCICcASKiEBRCCgCRQSgKBQQgaICUASKiEBRKCgCRQSgCBQRgaIQUASKiEBRKCICRUSgCBQRgaIQVASKiEARKCICRQGoCBQRgaJQRASKiFARKCICRQGoCBQRoSJQRASKglARKCICRaGoCBQBoSJQRASKglARKAICReCICBQBoSJQBASKgBARKAJCRaAICBQBoSJQBASKgBERKAJCRaAICBQBISJQBASKQBERKAJCRaAICBQBIyJQBASKQBEQKAJCRKAICBQBIyBQBISKQBEQKAJGQKAICBQBIiBQBISIQBEQKAJGQKAICBABIiBQAISAQAEQIABEQKAACBGBIiAQAIiAQAEQIAAEQIAACAGAAiAAAAiAAAEQAAAEQIAAEAAAAiAAAAiAAAEQAAAEQIAAEAAAAiAAAAiEAAEgAAAEQgAAEAAAAgAAAAgEAAAgAAAEAAAAEAAAAEAAAAgAAAAgAAAEAAAAEAgAAEAAAACAAAAgEAAAgAAAEAAAAEAgAACAAAAgAAAAgEAAAAAAAEAAAAAAgQAgAAAAgAAAAAAAAEAAAAAAgQAAAAAAgAAAAAAAAEAAAAAAAQAAAAAAgAAAAAACAAAAAAAAAQAAAAAAgAAAAAACAAAAAAAAAQAAAAQAAAAAAAACAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAIASkRICCghISUgpISUgJASUlJCSkZJCSk9paWntLSWntPSWlpKS+9pKT0/p6f1/JSf3/N7fl7P7/v5Pb//9/X8vN6f//N7fn/v7/v9//////8=";

const GOLDEN_ANGLE = Math.PI * (3 - Math.sqrt(5));

/** The i-th point of an N-point Fibonacci sphere, as latitude/longitude in degrees. */
export function fibonacciPoint(i: number, n: number = LAND_POINT_COUNT): { lat: number; lon: number } {
  const y = 1 - ((i + 0.5) * 2) / n;
  const theta = i * GOLDEN_ANGLE;
  return {
    lat: (Math.asin(y) * 180) / Math.PI,
    lon: (Math.atan2(Math.sin(theta), Math.cos(theta)) * 180) / Math.PI,
  };
}

/** Every land point, decoded from the mask. */
export function landPoints(): { lat: number; lon: number }[] {
  const bytes = Uint8Array.from(atob(LAND_MASK_B64), (c) => c.charCodeAt(0));
  const points: { lat: number; lon: number }[] = [];
  for (let i = 0; i < LAND_POINT_COUNT; i++) {
    if (bytes[i >> 3] & (1 << (i & 7))) points.push(fibonacciPoint(i));
  }
  return points;
}
