/**
 * Drives a real, live multi-turn adaptive interview against four canned
 * pilot personas (commuter, local, pay-focused, lifestyle-focused) and
 * dumps the full transcript + final profile for each to stdout (and to a
 * `.md` file per persona under this script's own directory) — the concrete
 * mechanism for Phase 2's "test against text transcripts before building
 * UI" requirement, and reused unchanged for Phase 6's pilot-review ask.
 *
 * Answers are hardcoded per persona, not generated by another LLM — this
 * tests the interview against realistic pilot answers, not the model
 * against itself. Since the interview branches dynamically, an answer
 * "matcher" makes a best-effort persona-appropriate choice for whatever
 * question actually comes back, falling back to a generic response for
 * anything a persona's own script didn't anticipate.
 *
 * Usage: npx tsx scripts/run-adaptive-interview-transcript.ts [persona...]
 * (no args runs all four). Requires ANTHROPIC_API_KEY in the environment —
 * never run in CI.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { computeBidPackGroundingStats } from "../src/lib/interview-grounding";
import {
  applyProfileUpdates,
  buildTurnRequest,
  finalizeAdaptiveProfile,
  HARD_CEILING_TURNS,
} from "../src/lib/interview-engine";
import { runInterviewTurn } from "../src/lib/interview-turn-service";
import { SAMPLE_BID_PACK } from "../src/lib/sample-bidpack";
import type {
  InterviewAnswer,
  InterviewQuestion,
  InterviewTurnRecord,
  PreferenceFact,
} from "../src/types/interview-session";
import type { CitySentiment } from "../src/types/preferences";

interface Persona {
  name: string;
  isCommuter: boolean;
  hasCrashPad: boolean | null;
  /** boundTo -> slider value (-100..100). Missing keys fall back to 0 (no strong preference). */
  sliderLeanings: Partial<Record<string, number>>;
  /** boundTo -> fraction of the bid pack's real range (0 = min, 1 = max). Missing keys fall back to 0.5. */
  targetLeanings: Partial<Record<string, number>>;
  /** Case-insensitive keywords this persona's choice-question answer should favor, checked against each option's label+description. */
  choiceKeywords: string[];
  /** Canned free-text answers, tried in order against the question prompt's own keywords; the last entry has no keyword and is the fallback. */
  freeTextAnswers: { keyword?: string; text: string }[];
  /**
   * Real IATA-style codes from SAMPLE_BID_PACK's own layover cities
   * (LAX/CDG/HNL) — mirrors the city picker's real pre-loop step
   * (`AdaptiveInterview.tsx`'s `factsFromCityPreferences`), which every
   * canned persona run before this one skipped entirely (this script never
   * simulated it), so none of them ever got a chance to exercise the
   * "why" follow-up or city-reason tagging the real UI always has a shot
   * at. Absent means no cities seeded, exactly like before.
   */
  citySeed?: Record<string, CitySentiment>;
}

/** Mirrors `AdaptiveInterview.tsx`'s own `factsFromCityPreferences` exactly — kept as a separate small copy here since that one lives in a "use client" component file this Node script can't import from. */
function factsFromCitySeed(citySeed: Record<string, CitySentiment>): PreferenceFact[] {
  return Object.entries(citySeed).map(([code, sentiment]) => ({
    id: crypto.randomUUID(),
    statement: `${sentiment === "love" ? "Loves" : "Wants to avoid"} layovers in ${code}.`,
    kind: "measurable",
    measurable: { type: "city-sentiment", code, sentiment },
    confidence: 1,
    importance: 0.6,
    source: { kind: "seed-question", questionKey: "cities" },
    turnIndex: 0,
  }));
}

const PERSONAS: Persona[] = [
  {
    name: "commuter",
    isCommuter: true,
    hasCrashPad: false,
    sliderLeanings: { tripLength: 45, reportTime: 20, deadheadTolerance: 55, creditHours: 10 },
    targetLeanings: { departures: 0.15, daysOff: 0.6 },
    choiceKeywords: ["commute", "fewer", "longer", "minimize", "in a row", "consolidat"],
    freeTextAnswers: [
      { keyword: "deadhead", text: "A deadhead on either end actually helps me — it gets me positioned without burning a day off flying myself out here on my own dime." },
      { keyword: "report", text: "I'm flying in the night before regardless, so the report time itself doesn't hit me the way it would someone driving in that morning." },
      { text: "I commute in from out of state, so fewer separate trips matters more to me than almost anything else — every extra departure is another commute I'm paying for in time and money." },
    ],
  },
  {
    name: "local",
    isCommuter: false,
    hasCrashPad: null,
    sliderLeanings: { tripLength: -25, deadheadTolerance: -35, reportTime: -5 },
    targetLeanings: { departures: 0.7, daysOff: 0.55 },
    choiceKeywords: ["shorter", "home", "domestic", "frequent"],
    freeTextAnswers: [
      { keyword: "deadhead", text: "I'd rather fly it myself than ride along — I'm based here, so there's no commuting angle making a deadhead worth anything to me." },
      { text: "I'm local, so more frequent shorter trips are actually fine by me — I'm sleeping at home either way in between." },
    ],
  },
  {
    name: "pay-focused",
    isCommuter: false,
    hasCrashPad: null,
    sliderLeanings: { creditHours: 85, daysOff: -30, circadianHealth: -35, tripLength: 15 },
    targetLeanings: { creditHours: 0.9 },
    choiceKeywords: ["credit", "pay", "busier", "extra", "more hours"],
    freeTextAnswers: [
      { keyword: "sleep", text: "I'd rather push through a rough circadian trip than leave credit on the table — I can catch up on rest on my days off." },
      { text: "Bottom line, I'm bidding this line to maximize what it pays. If a trip's busy but it pays well, that's a win for me, not a downside." },
    ],
  },
  {
    name: "lifestyle-focused",
    isCommuter: false,
    hasCrashPad: null,
    sliderLeanings: { creditHours: -40, daysOff: 65, circadianHealth: 70, tripLength: -30, hotelQuality: 55 },
    targetLeanings: { daysOff: 0.75, creditHours: 0.15 },
    choiceKeywords: ["lifestyle", "lighter", "downtime", "rest", "fewer duty hours", "home"],
    freeTextAnswers: [
      // Deliberately unambiguous refusal language (Phase 4 validation of the
      // Satisfaction Index's dealbreaker detection) — checked first since
      // pickFreeText takes the first keyword match, and "red-eye" is likely
      // to appear in whatever circadian-adjacent question this persona's
      // strong circadianHealth lean provokes.
      { keyword: "0300", text: "A red-eye departure is an absolute dealbreaker for me — I will not accept a line with one, full stop, no matter what else it offers." },
      { keyword: "back-of-clock", text: "A red-eye departure is an absolute dealbreaker for me — I will not accept a line with one, full stop, no matter what else it offers." },
      { keyword: "early-side", text: "A red-eye departure is an absolute dealbreaker for me — I will not accept a line with one, full stop, no matter what else it offers." },
      { keyword: "credit", text: "I'll take a leaner line every time if it means a schedule I actually enjoy living with — I'm not trying to max out hours this point in my career." },
      { text: "Protecting my sleep and having real predictable time off matters a lot more to me than squeezing out extra pay." },
    ],
  },
  {
    // Deliberately the richest, most specific persona in the set: a
    // mid-seniority local FO who has an opinion on nearly every plausible
    // topic and expresses it with concrete, distinguishable language
    // instead of one or two boilerplate lines repeated under different
    // questions. Built to test whether answer depth/specificity —
    // not just directional leanings — measurably reduces the
    // rephrase-and-give-up turns and produces richer qualitative facts,
    // a sane circadianTolerance, and populated city-preference reasons
    // (via `citySeed`, which none of the four personas above exercise).
    name: "deep",
    isCommuter: false,
    hasCrashPad: true,
    sliderLeanings: {
      tripLength: 30,
      reportTime: -20,
      deadheadTolerance: 25,
      creditHours: 40,
      circadianHealth: 45,
      hotelQuality: 60,
      international: 55,
      landings: -25,
      riskTolerance: -20,
      adminEffortAppetite: -35,
    },
    targetLeanings: { daysOff: 0.65, creditHours: 0.7, departures: 0.35, circadianTolerance: 0.15 },
    citySeed: { LAX: "love", HNL: "love", CDG: "avoid" },
    choiceKeywords: ["international", "wide-body", "predictable", "consistent", "same", "quiet", "low", "few"],
    freeTextAnswers: [
      {
        keyword: "hnl",
        text: "Honolulu is my favorite layover on the system, hands down — the crew hotel is walkable to the beach, the weather's a guaranteed break from whatever's happening back home, and the time change is mild enough that I actually sleep well there instead of fighting it.",
      },
      {
        keyword: "lax",
        text: "LAX works great for me specifically because it's a same-night connection to my crash pad — I'm not paying for a hotel or losing a day, so even a short layover there is basically free time off.",
      },
      {
        keyword: "cdg",
        text: "I actively try to avoid Paris turns — it's not the city, it's that the layover is just long enough to wreck my sleep schedule for the next three days but too short to actually enjoy being there, so it's the worst of both.",
      },
      {
        keyword: "report",
        text: "A single early report I can absorb fine, especially if I know it's coming and can pre-adapt the night before. Two in a row is where my sleep debt actually starts to show up in the cockpit, and I try hard to never bid a third.",
      },
      {
        keyword: "0300",
        text: "A single early report I can absorb fine, especially if I know it's coming and can pre-adapt the night before. Two in a row is where my sleep debt actually starts to show up in the cockpit, and I try hard to never bid a third.",
      },
      {
        keyword: "consecutive",
        text: "One early report is a non-issue for me. By the second one back-to-back I'm noticeably running on a deficit, and that's the real ceiling — I don't think I've ever handled three well even when the schedule forced it.",
      },
      {
        keyword: "deadhead",
        text: "A deadhead on the front end of a trip is genuinely useful to me if it lands me somewhere better positioned for the flying, but a deadhead tacked onto the back end just to get me home feels like a wasted duty period I'd rather not have at all.",
      },
      {
        keyword: "day-rig",
        text: "I care less about the day-rig ratio in isolation and more about whether the credit reflects the actual time I'm away from home — a trip that pays light for how many days it eats is the one that annoys me, regardless of the exact ratio.",
      },
      {
        keyword: "duty",
        text: "Long duty days don't bother me much as long as there's a real, protected rest period on the back end — it's back-to-back short-rest turns that actually grind on me, not one long day by itself.",
      },
      {
        keyword: "reserve",
        text: "Reserve is fine in small doses but I structure my whole bid to avoid heavy reserve months — the unpredictability costs me more in disrupted plans than the schedule flexibility is worth.",
      },
      {
        keyword: "predictab",
        text: "I'd take a slightly worse but consistent schedule over a better one that changes every month — being able to actually plan my life outside work matters more to me at this point in my career than optimizing every single line.",
      },
      {
        keyword: "hotel",
        text: "A quiet room and a real gym or at least a walkable area to run in the morning matters a lot to me — I'm in these hotels enough that the difference between a good one and a bad one genuinely affects how I feel flying the next leg.",
      },
      {
        keyword: "noise",
        text: "Room noise is a bigger deal for me than most people probably admit — a loud hotel on a short layover means I land the next leg genuinely tired, not just annoyed.",
      },
      {
        keyword: "international",
        text: "I actively seek out the international trips — the pay premium is nice but honestly I'd take them even at parity, I just enjoy that flying more than the short domestic turns.",
      },
      {
        keyword: "landing",
        text: "I don't chase landings the way some guys do — currency is currency, I'd rather have fewer, longer legs than a bunch of short hops just to pad the count.",
      },
      {
        keyword: "risk",
        text: "I bid conservatively — I'd rather hold a line I know I can fly reliably than reach for something that might get pulled out from under me and leave me scrambling on reserve instead.",
      },
      {
        keyword: "admin",
        text: "I'll take a schedule with a little less pay if it means less paperwork and fewer logistics headaches on my end — trip-trading and re-optimizing every month isn't how I want to spend my off days.",
      },
      {
        keyword: "financ",
        text: "I'm past the phase of my career where I need every trip to max out credit — steady, comfortable pay with a schedule I actually enjoy living inside of is worth more to me now than squeezing out the last few hours.",
      },
      {
        keyword: "family",
        text: "Being reliably home on the same days each month matters more to me than any single trip's pay — my family plans around my schedule and last-minute changes cost me more goodwill at home than they're worth.",
      },
      {
        keyword: "grocery",
        text: "Being near a real grocery store or walkable food options on a longer layover makes a bigger difference to how I feel than people give it credit for — living off hotel room service for three days wears on me.",
      },
      {
        text: "Overall I'd describe myself as someone who optimizes for a stable, predictable schedule with good international layovers, protects my sleep aggressively, and is willing to give up some raw credit and admin flexibility to get all of that.",
      },
    ],
  },
];

function pickSliderValue(persona: Persona, boundTo: string): number {
  return persona.sliderLeanings[boundTo] ?? 0;
}

function pickTargetValue(persona: Persona, boundTo: string, min: number, max: number): number {
  const fraction = persona.targetLeanings[boundTo] ?? 0.5;
  return Math.round(min + (max - min) * fraction);
}

function pickChoiceIndex(persona: Persona, options: { label: string; description?: string }[]): number {
  let bestIndex = 0;
  let bestScore = -1;
  options.forEach((opt, i) => {
    const text = `${opt.label} ${opt.description ?? ""}`.toLowerCase();
    const score = persona.choiceKeywords.filter((kw) => text.includes(kw.toLowerCase())).length;
    if (score > bestScore) {
      bestScore = score;
      bestIndex = i;
    }
  });
  return bestIndex;
}

function pickFreeText(persona: Persona, prompt: string): string {
  const lower = prompt.toLowerCase();
  const match = persona.freeTextAnswers.find((a) => a.keyword && lower.includes(a.keyword));
  return (match ?? persona.freeTextAnswers[persona.freeTextAnswers.length - 1]).text;
}

function answerQuestion(persona: Persona, question: InterviewQuestion, creditRange: { min: number; max: number }): InterviewAnswer {
  switch (question.kind) {
    case "slider":
      return { kind: "slider", value: pickSliderValue(persona, question.boundTo) };
    case "target-slider": {
      // circadianTolerance is a small, fixed [0, 4] "how many consecutive
      // early reports" count — not a bid-pack-derived range. Mirrors
      // `AdaptiveInterview.tsx`'s own `CIRCADIAN_TOLERANCE_RANGE`, which this
      // harness previously ignored (falling through to the generic 4-20
      // default and producing nonsensical values like "12 in a row").
      const range =
        question.boundTo === "creditHours"
          ? creditRange
          : question.boundTo === "circadianTolerance"
            ? { min: 0, max: 4 }
            : { min: 4, max: 20 };
      return { kind: "target-slider", value: pickTargetValue(persona, question.boundTo, range.min, range.max) };
    }
    case "choice":
      return { kind: "choice", selectedIndex: pickChoiceIndex(persona, question.options) };
    case "free-text":
      return { kind: "free-text", text: pickFreeText(persona, question.prompt) };
    case "wrap-up":
      return { kind: "skipped" };
  }
}

function formatAnswer(question: InterviewQuestion, answer: InterviewAnswer): string {
  if (answer.kind === "choice" && question.kind === "choice") {
    return question.options[answer.selectedIndex]?.label ?? "(invalid choice)";
  }
  if (answer.kind === "slider") return String(answer.value);
  if (answer.kind === "target-slider") return String(answer.value);
  if (answer.kind === "free-text") return answer.text;
  return "(skipped)";
}

async function runPersona(persona: Persona): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set.");

  const grounding = computeBidPackGroundingStats(SAMPLE_BID_PACK);
  let transcript: InterviewTurnRecord[] = [];
  let facts: PreferenceFact[] = persona.citySeed ? factsFromCitySeed(persona.citySeed) : [];
  let turnsUsed = 0;
  const lines: string[] = [`# Adaptive interview transcript — persona: ${persona.name}\n`];

  while (turnsUsed < HARD_CEILING_TURNS) {
    const request = buildTurnRequest({
      transcript,
      facts,
      grounding,
      base: SAMPLE_BID_PACK.base,
      aircraft: SAMPLE_BID_PACK.aircraft,
      isCommuter: persona.isCommuter,
      turnsUsed,
    });

    const result = await runInterviewTurn(apiKey, request);
    if (!result.ok) {
      lines.push(`\n**Turn ${turnsUsed + 1} failed: ${result.error}**\n`);
      break;
    }
    const { turn } = result;
    facts = applyProfileUpdates(facts, turn.profileUpdates);

    if (turn.reasoning) {
      lines.push(`\n_Reasoning: ${turn.reasoning}_`);
    }

    if (turn.action === "wrap_up" || !turn.question) {
      lines.push(`\n**Interview wrapped up after ${turnsUsed} question${turnsUsed === 1 ? "" : "s"}.**\n`);
      break;
    }

    const answer = answerQuestion(persona, turn.question, grounding.creditHours);
    lines.push(`\n**Q${turnsUsed + 1} (${turn.question.kind}):** ${turn.question.prompt}`);
    if (turn.question.kind === "slider") {
      lines.push(`_(${turn.question.lowLabel} .. ${turn.question.centerLabel} .. ${turn.question.highLabel})_`);
    }
    lines.push(`**A:** ${formatAnswer(turn.question, answer)}`);

    transcript = [
      ...transcript,
      { turnIndex: turnsUsed, question: turn.question, answer, profileFactIdsTouched: [] },
    ];
    turnsUsed++;
  }

  if (turnsUsed >= HARD_CEILING_TURNS) {
    lines.push(`\n**Hit the hard turn ceiling (${HARD_CEILING_TURNS}) — stopped client-side regardless of model intent.**\n`);
  }

  const profile = finalizeAdaptiveProfile({
    facts,
    transcript,
    isCommuter: persona.isCommuter,
    hasCrashPad: persona.hasCrashPad,
    cityPreferencesSeed: persona.citySeed,
  });

  lines.push(`\n## Final profile\n`);
  lines.push("```json");
  lines.push(
    JSON.stringify(
      {
        weights: profile.weights,
        explicitTargets: profile.explicitTargets,
        cityPreferences: profile.cityPreferences,
        implicitWeights: profile.implicitWeights,
        qualitativeFacts: profile.discoveredFacts.filter((f) => f.kind === "qualitative").map((f) => f.statement),
        dealbreakers: profile.discoveredFacts
          .filter((f) => f.severity === "dealbreaker")
          .map((f) => ({ statement: f.statement, measurable: f.measurable })),
      },
      null,
      2
    )
  );
  lines.push("```");

  return lines.join("\n");
}

async function main() {
  const requested = process.argv.slice(2);
  const personas = requested.length > 0 ? PERSONAS.filter((p) => requested.includes(p.name)) : PERSONAS;
  if (personas.length === 0) {
    console.error(`No matching persona. Available: ${PERSONAS.map((p) => p.name).join(", ")}`);
    process.exit(1);
  }

  for (const persona of personas) {
    console.log(`\n=== Running persona: ${persona.name} ===`);
    const transcript = await runPersona(persona);
    console.log(transcript);
    const outPath = path.join(__dirname, `transcript-${persona.name}.md`);
    await writeFile(outPath, transcript, "utf-8");
    console.log(`\n(written to ${outPath})`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
