/**
 * Drives a real, live multi-turn adaptive interview against four canned
 * pilot personas (commuter, local, pay-focused, lifestyle-focused) and
 * dumps the full transcript + final profile for each to stdout (and to a
 * `.md` file per persona under this script's own directory) — the concrete
 * mechanism for Phase 2's "test against text transcripts before building
 * UI" requirement, and reused unchanged for Phase 6's pilot-review ask.
 *
 * Answers are hardcoded per persona, not generated by another LLM — this
 * tests the interview against realistic pilot answers, not the model
 * against itself. Since the interview branches dynamically, an answer
 * "matcher" makes a best-effort persona-appropriate choice for whatever
 * question actually comes back, falling back to a generic response for
 * anything a persona's own script didn't anticipate.
 *
 * Usage: npx tsx scripts/run-adaptive-interview-transcript.ts [persona...]
 * (no args runs all four). Requires ANTHROPIC_API_KEY in the environment —
 * never run in CI.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";
import { computeBidPackGroundingStats } from "../src/lib/interview-grounding";
import {
  applyProfileUpdates,
  buildTurnRequest,
  finalizeAdaptiveProfile,
  HARD_CEILING_TURNS,
} from "../src/lib/interview-engine";
import { runInterviewTurn } from "../src/lib/interview-turn-service";
import { SAMPLE_BID_PACK } from "../src/lib/sample-bidpack";
import type {
  InterviewAnswer,
  InterviewQuestion,
  InterviewTurnRecord,
  PreferenceFact,
} from "../src/types/interview-session";

interface Persona {
  name: string;
  isCommuter: boolean;
  hasCrashPad: boolean | null;
  /** boundTo -> slider value (-100..100). Missing keys fall back to 0 (no strong preference). */
  sliderLeanings: Partial<Record<string, number>>;
  /** boundTo -> fraction of the bid pack's real range (0 = min, 1 = max). Missing keys fall back to 0.5. */
  targetLeanings: Partial<Record<string, number>>;
  /** Case-insensitive keywords this persona's choice-question answer should favor, checked against each option's label+description. */
  choiceKeywords: string[];
  /** Canned free-text answers, tried in order against the question prompt's own keywords; the last entry has no keyword and is the fallback. */
  freeTextAnswers: { keyword?: string; text: string }[];
}

const PERSONAS: Persona[] = [
  {
    name: "commuter",
    isCommuter: true,
    hasCrashPad: false,
    sliderLeanings: { tripLength: 45, reportTime: 20, deadheadTolerance: 55, creditHours: 10 },
    targetLeanings: { departures: 0.15, daysOff: 0.6 },
    choiceKeywords: ["commute", "fewer", "longer", "minimize", "in a row", "consolidat"],
    freeTextAnswers: [
      { keyword: "deadhead", text: "A deadhead on either end actually helps me — it gets me positioned without burning a day off flying myself out here on my own dime." },
      { keyword: "report", text: "I'm flying in the night before regardless, so the report time itself doesn't hit me the way it would someone driving in that morning." },
      { text: "I commute in from out of state, so fewer separate trips matters more to me than almost anything else — every extra departure is another commute I'm paying for in time and money." },
    ],
  },
  {
    name: "local",
    isCommuter: false,
    hasCrashPad: null,
    sliderLeanings: { tripLength: -25, deadheadTolerance: -35, reportTime: -5 },
    targetLeanings: { departures: 0.7, daysOff: 0.55 },
    choiceKeywords: ["shorter", "home", "domestic", "frequent"],
    freeTextAnswers: [
      { keyword: "deadhead", text: "I'd rather fly it myself than ride along — I'm based here, so there's no commuting angle making a deadhead worth anything to me." },
      { text: "I'm local, so more frequent shorter trips are actually fine by me — I'm sleeping at home either way in between." },
    ],
  },
  {
    name: "pay-focused",
    isCommuter: false,
    hasCrashPad: null,
    sliderLeanings: { creditHours: 85, daysOff: -30, circadianHealth: -35, tripLength: 15 },
    targetLeanings: { creditHours: 0.9 },
    choiceKeywords: ["credit", "pay", "busier", "extra", "more hours"],
    freeTextAnswers: [
      { keyword: "sleep", text: "I'd rather push through a rough circadian trip than leave credit on the table — I can catch up on rest on my days off." },
      { text: "Bottom line, I'm bidding this line to maximize what it pays. If a trip's busy but it pays well, that's a win for me, not a downside." },
    ],
  },
  {
    name: "lifestyle-focused",
    isCommuter: false,
    hasCrashPad: null,
    sliderLeanings: { creditHours: -40, daysOff: 65, circadianHealth: 70, tripLength: -30, hotelQuality: 55 },
    targetLeanings: { daysOff: 0.75, creditHours: 0.15 },
    choiceKeywords: ["lifestyle", "lighter", "downtime", "rest", "fewer duty hours", "home"],
    freeTextAnswers: [
      // Deliberately unambiguous refusal language (Phase 4 validation of the
      // Satisfaction Index's dealbreaker detection) — checked first since
      // pickFreeText takes the first keyword match, and "red-eye" is likely
      // to appear in whatever circadian-adjacent question this persona's
      // strong circadianHealth lean provokes.
      { keyword: "0300", text: "A red-eye departure is an absolute dealbreaker for me — I will not accept a line with one, full stop, no matter what else it offers." },
      { keyword: "back-of-clock", text: "A red-eye departure is an absolute dealbreaker for me — I will not accept a line with one, full stop, no matter what else it offers." },
      { keyword: "early-side", text: "A red-eye departure is an absolute dealbreaker for me — I will not accept a line with one, full stop, no matter what else it offers." },
      { keyword: "credit", text: "I'll take a leaner line every time if it means a schedule I actually enjoy living with — I'm not trying to max out hours this point in my career." },
      { text: "Protecting my sleep and having real predictable time off matters a lot more to me than squeezing out extra pay." },
    ],
  },
];

function pickSliderValue(persona: Persona, boundTo: string): number {
  return persona.sliderLeanings[boundTo] ?? 0;
}

function pickTargetValue(persona: Persona, boundTo: string, min: number, max: number): number {
  const fraction = persona.targetLeanings[boundTo] ?? 0.5;
  return Math.round(min + (max - min) * fraction);
}

function pickChoiceIndex(persona: Persona, options: { label: string; description?: string }[]): number {
  let bestIndex = 0;
  let bestScore = -1;
  options.forEach((opt, i) => {
    const text = `${opt.label} ${opt.description ?? ""}`.toLowerCase();
    const score = persona.choiceKeywords.filter((kw) => text.includes(kw.toLowerCase())).length;
    if (score > bestScore) {
      bestScore = score;
      bestIndex = i;
    }
  });
  return bestIndex;
}

function pickFreeText(persona: Persona, prompt: string): string {
  const lower = prompt.toLowerCase();
  const match = persona.freeTextAnswers.find((a) => a.keyword && lower.includes(a.keyword));
  return (match ?? persona.freeTextAnswers[persona.freeTextAnswers.length - 1]).text;
}

function answerQuestion(persona: Persona, question: InterviewQuestion, creditRange: { min: number; max: number }): InterviewAnswer {
  switch (question.kind) {
    case "slider":
      return { kind: "slider", value: pickSliderValue(persona, question.boundTo) };
    case "target-slider": {
      const range = question.boundTo === "creditHours" ? creditRange : { min: 4, max: 20 };
      return { kind: "target-slider", value: pickTargetValue(persona, question.boundTo, range.min, range.max) };
    }
    case "choice":
      return { kind: "choice", selectedIndex: pickChoiceIndex(persona, question.options) };
    case "free-text":
      return { kind: "free-text", text: pickFreeText(persona, question.prompt) };
    case "wrap-up":
      return { kind: "skipped" };
  }
}

function formatAnswer(question: InterviewQuestion, answer: InterviewAnswer): string {
  if (answer.kind === "choice" && question.kind === "choice") {
    return question.options[answer.selectedIndex]?.label ?? "(invalid choice)";
  }
  if (answer.kind === "slider") return String(answer.value);
  if (answer.kind === "target-slider") return String(answer.value);
  if (answer.kind === "free-text") return answer.text;
  return "(skipped)";
}

async function runPersona(persona: Persona): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set.");

  const grounding = computeBidPackGroundingStats(SAMPLE_BID_PACK);
  let transcript: InterviewTurnRecord[] = [];
  let facts: PreferenceFact[] = [];
  let turnsUsed = 0;
  const lines: string[] = [`# Adaptive interview transcript — persona: ${persona.name}\n`];

  while (turnsUsed < HARD_CEILING_TURNS) {
    const request = buildTurnRequest({
      transcript,
      facts,
      grounding,
      base: SAMPLE_BID_PACK.base,
      aircraft: SAMPLE_BID_PACK.aircraft,
      isCommuter: persona.isCommuter,
      turnsUsed,
    });

    const result = await runInterviewTurn(apiKey, request);
    if (!result.ok) {
      lines.push(`\n**Turn ${turnsUsed + 1} failed: ${result.error}**\n`);
      break;
    }
    const { turn } = result;
    facts = applyProfileUpdates(facts, turn.profileUpdates);

    if (turn.reasoning) {
      lines.push(`\n_Reasoning: ${turn.reasoning}_`);
    }

    if (turn.action === "wrap_up" || !turn.question) {
      lines.push(`\n**Interview wrapped up after ${turnsUsed} question${turnsUsed === 1 ? "" : "s"}.**\n`);
      break;
    }

    const answer = answerQuestion(persona, turn.question, grounding.creditHours);
    lines.push(`\n**Q${turnsUsed + 1} (${turn.question.kind}):** ${turn.question.prompt}`);
    if (turn.question.kind === "slider") {
      lines.push(`_(${turn.question.lowLabel} .. ${turn.question.centerLabel} .. ${turn.question.highLabel})_`);
    }
    lines.push(`**A:** ${formatAnswer(turn.question, answer)}`);

    transcript = [
      ...transcript,
      { turnIndex: turnsUsed, question: turn.question, answer, profileFactIdsTouched: [] },
    ];
    turnsUsed++;
  }

  if (turnsUsed >= HARD_CEILING_TURNS) {
    lines.push(`\n**Hit the hard turn ceiling (${HARD_CEILING_TURNS}) — stopped client-side regardless of model intent.**\n`);
  }

  const profile = finalizeAdaptiveProfile({
    facts,
    transcript,
    isCommuter: persona.isCommuter,
    hasCrashPad: persona.hasCrashPad,
  });

  lines.push(`\n## Final profile\n`);
  lines.push("```json");
  lines.push(
    JSON.stringify(
      {
        weights: profile.weights,
        explicitTargets: profile.explicitTargets,
        cityPreferences: profile.cityPreferences,
        implicitWeights: profile.implicitWeights,
        qualitativeFacts: profile.discoveredFacts.filter((f) => f.kind === "qualitative").map((f) => f.statement),
        dealbreakers: profile.discoveredFacts
          .filter((f) => f.severity === "dealbreaker")
          .map((f) => ({ statement: f.statement, measurable: f.measurable })),
      },
      null,
      2
    )
  );
  lines.push("```");

  return lines.join("\n");
}

async function main() {
  const requested = process.argv.slice(2);
  const personas = requested.length > 0 ? PERSONAS.filter((p) => requested.includes(p.name)) : PERSONAS;
  if (personas.length === 0) {
    console.error(`No matching persona. Available: ${PERSONAS.map((p) => p.name).join(", ")}`);
    process.exit(1);
  }

  for (const persona of personas) {
    console.log(`\n=== Running persona: ${persona.name} ===`);
    const transcript = await runPersona(persona);
    console.log(transcript);
    const outPath = path.join(__dirname, `transcript-${persona.name}.md`);
    await writeFile(outPath, transcript, "utf-8");
    console.log(`\n(written to ${outPath})`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
